In [6]:
from FTXWebsocket import FTXWebsocket
import json

def on_message(ws, msg):
    msg_data = json.loads(msg)
    if msg_data['type'] == 'update':
        for raw_trade in msg_data['data']:
            trade = {'time': raw_trade['time']}
            print(trade['price'], trade)
            
def on_close(ws):
    print("CLOSED")

ws = FTXWebsocket(channel="trades", market="BTC-PERP", on_message = on_message, on_close = on_close)
ws.run()

50765.0 {'id': 2733644069, 'price': 50765.0, 'size': 0.0044, 'side': 'sell', 'liquidation': False, 'time': '2021-12-08T15:40:55.113081+00:00'}
50765.0 {'id': 2733644070, 'price': 50765.0, 'size': 0.2588, 'side': 'sell', 'liquidation': False, 'time': '2021-12-08T15:40:55.113081+00:00'}
50765.0 {'id': 2733644096, 'price': 50765.0, 'size': 0.005, 'side': 'sell', 'liquidation': False, 'time': '2021-12-08T15:40:55.238496+00:00'}
50765.0 {'id': 2733644097, 'price': 50765.0, 'size': 1.0659, 'side': 'sell', 'liquidation': False, 'time': '2021-12-08T15:40:55.240289+00:00'}
50765.0 {'id': 2733644133, 'price': 50765.0, 'size': 0.1, 'side': 'sell', 'liquidation': False, 'time': '2021-12-08T15:40:55.305677+00:00'}
50765.0 {'id': 2733644147, 'price': 50765.0, 'size': 0.003, 'side': 'sell', 'liquidation': False, 'time': '2021-12-08T15:40:55.395193+00:00'}
50754.0 {'id': 2733644242, 'price': 50754.0, 'size': 0.04, 'side': 'buy', 'liquidation': False, 'time': '2021-12-08T15:40:56.026197+00:00'}

In [1]:
from CandleSeries import CandleSeries
a = CandleSeries('BTC-PERP', 60, 2)
a.dump_to_csv()

In [69]:
import pandas as pd
ts = pd.to_datetime("2021-12-08T16:35:00+00:00", utc = True)
_ts = "2021-12-08T15:46:00+00:00"

#df.loc[pd.Index(["cobra", "viper"], name="foo")]

#a.candle_data.loc[[ts], ["open"]]
new_row = {'open':1, 'high':10, 'low': 0.5, 'close': 5, 'volume':30}
a.candle_data.iloc[-1:]
a.candle_data.append(pd.DataFrame(new_row, index=[ts]))
a.candle_data
a.candle_data.at[ts, "newcol"] = "funk"

In [71]:
a.candle_data

,open,high,low,close,volume,newcol
startTime,,,,,,
2021-12-08 17:58:00+00:00,50276.0,50319.0,50258.0,50312.0,788926.5169,NaN
2021-12-08 17:59:00+00:00,50312.0,50313.0,50306.0,50311.0,184504.4703,NaN
2021-12-08 16:35:00+00:00,NaN,NaN,NaN,NaN,NaN,funk

In [19]:
import pandas as pd
ts = pd.to_datetime("2021-12-08T16:35:00+00:00", utc = True)
_ts = "2021-12-08T15:46:00+00:00"

#df.loc[pd.Index(["cobra", "viper"], name="foo")]

#a.candle_data.loc[[ts], ["open"]]
new_row = {'open':1, 'high':10, 'low': 0.5, 'close': 5, 'volume':30}
a.candle_data.iloc[-1:]
b = pd.concat([a.candle_data, pd.DataFrame(new_row, index=[ts])], axis=0)
b

                              open     high      low    close        volume
2021-12-08 16:19:00+00:00  50597.0  50640.0  50580.0  50617.0  1.980695e+06
2021-12-08 16:20:00+00:00  50617.0  50618.0  50548.0  50618.0  3.321566e+06
2021-12-08 16:21:00+00:00  50618.0  50673.0  50618.0  50654.0  1.034889e+06
2021-12-08 16:22:00+00:00  50654.0  50683.0  50652.0  50654.0  6.972459e+05
2021-12-08 16:23:00+00:00  50654.0  50654.0  50576.0  50614.0  2.277001e+06
2021-12-08 16:24:00+00:00  50614.0  50653.0  50608.0  50645.0  1.437361e+06
2021-12-08 16:25:00+00:00  50645.0  50666.0  50617.0  50628.0  6.416425e+05
2021-12-08 16:26:00+00:00  50628.0  50641.0  50619.0  50629.0  1.445979e+06
2021-12-08 16:27:00+00:00  50629.0  50636.0  50588.0  50611.0  2.676100e+06
2021-12-08 16:28:00+00:00  50611.0  50636.0  50587.0  50609.0  1.410799e+06
2021-12-08 16:35:00+00:00      1.0     10.0      0.5      5.0  3.000000e+01

In [62]:
variances = {}
variances['open_var'] = 1
variances['high_var'] = 2
variances['low_var'] = 3
variances['close_var'] = 4
variances['volume_var'] = 5

In [64]:
pd.concat([b, pd.DataFrame(variances, index=[ts])], axis=1)

,open,high,low,close,volume,open_var,high_var,low_var,close_var,volume_var
2021-12-08 16:19:00+00:00,50597.0,50640.0,50580.0,50617.0,1.980695e+06,NaN,NaN,NaN,NaN,NaN
2021-12-08 16:20:00+00:00,50617.0,50618.0,50548.0,50618.0,3.321566e+06,NaN,NaN,NaN,NaN,NaN
2021-12-08 16:21:00+00:00,50618.0,50673.0,50618.0,50654.0,1.034889e+06,NaN,NaN,NaN,NaN,NaN
2021-12-08 16:22:00+00:00,50654.0,50683.0,50652.0,50654.0,6.972459e+05,NaN,NaN,NaN,NaN,NaN
2021-12-08 16:23:00+00:00,50654.0,50654.0,50576.0,50614.0,2.277001e+06,NaN,NaN,NaN,NaN,NaN
2021-12-08 16:24:00+00:00,50614.0,50653.0,50608.0,50645.0,1.437361e+06,NaN,NaN,NaN,NaN,NaN
2021-12-08 16:25:00+00:00,50645.0,50666.0,50617.0,50628.0,6.416425e+05,NaN,NaN,NaN,NaN,NaN
2021-12-08 16:26:00+00:00,50628.0,50641.0,50619.0,50629.0,1.445979e+06,NaN,NaN,NaN,NaN,NaN
2021-12-08 16:27:00+00:00,50629.0,50636.0,50588.0,50611.0,2.676100e+06,NaN,NaN,NaN,NaN,NaN
2021-12-08 16:28:00+00:00,50611.0,50636.0,50587.0,50609.0,1.410799e+06,NaN,NaN,NaN,NaN,NaN
2021-12-08 16:35:00+00:00,6.0,10.0,0.5,5.0,3.000000e+01,1.0,2.0,3.0,4.0,5.0

In [61]:
b.at["x", "open"]

KeyError: 'x'